### ISSUE TITLE
plz use Access-Control-Allow-Origin to * in api

### ISSUE THREAD

**Issue by Knob123** [harrynull/random_anime_wallpaper#2]

**Comment by harrynull** [comment]
I did not add this because it is intended that you host this on your own server. This is mostly because that 1) I do not have any promise of running this reliably 24*7, 2) The API might change in the future, 3) If you do download=true, it will incur bandwidth cost for my server.

I dont think it's super hard to set up and I saw a fork with docker supports at https://github.com/lideming/random_anime_wallpaper (not tested)

Please re-open if there is any other question or have a legit use case
